# Generated by Django 4.0.4 on 2022-07-09 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_alter_profile_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('upvote', models.BooleanField(blank=True, default=False, null=True)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('upvote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Story_Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
