# Generated by Django 4.0.4 on 2022-08-23 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import story.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('tag_username', models.CharField(blank=True, max_length=500, null=True)),
                ('comment_id', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment', to='story.comment')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Story_Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('url', models.ImageField(blank=True, null=True, upload_to=story.models.set_story_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif', 'bmp', 'jpg', 'jpeg', 'gif', 'png', 'eps'])])),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
            ],
            options={
                'db_table': 'Story_Photo',
            },
        ),
        migrations.CreateModel(
            name='Saved_Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'Saved_Story',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.comment')),
                ('story', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Comment_Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('url', models.ImageField(blank=True, null=True, upload_to=story.models.set_comment_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif', 'bmp', 'jpg', 'jpeg', 'gif', 'png', 'eps'])])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.comment')),
            ],
            options={
                'db_table': 'Comment_Photo',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='story_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
