# Generated by Django 4.0.4 on 2022-07-09 00:18

import django.core.validators
from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_photo',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=story.models.set_comment_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif', 'bmp', 'jpg', 'jpeg', 'gif', 'png', 'eps'])]),
        ),
        migrations.AddField(
            model_name='story_photo',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=story.models.set_story_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif', 'bmp', 'jpg', 'jpeg', 'gif', 'png', 'eps'])]),
        ),
    ]
