# Generated by Django 4.0.4 on 2022-07-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_comment_photo_images_story_photo_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
