# Generated by Django 4.0.4 on 2022-07-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_comment_story'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment_photo',
            table='Comment_Photo',
        ),
        migrations.AlterModelTable(
            name='story_photo',
            table='Story_Photo',
        ),
    ]
