# Generated by Django 4.0.4 on 2022-07-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_comment_photo_table_alter_story_photo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_photo',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='story_photo',
            old_name='images',
            new_name='image',
        ),
    ]
