# Generated by Django 4.0.4 on 2022-07-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_rename_images_comment_photo_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story_photo',
            old_name='image',
            new_name='url',
        ),
    ]
