# Generated by Django 4.0.4 on 2022-07-18 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_rename_image_story_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_photo',
            old_name='image',
            new_name='url',
        ),
        migrations.AddField(
            model_name='comment_photo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment_photo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='story_photo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
