# Generated by Django 4.0.4 on 2022-07-21 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import story.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_background_image'),
        ('story', '0009_rename_image_comment_photo_url_comment_photo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=story.models.set_story_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif', 'bmp', 'jpg', 'jpeg', 'gif', 'png', 'eps'])]),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.comment')),
                ('story', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_followeed', to='user.profile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_follower', to='user.profile')),
            ],
            options={
                'db_table': 'Follow',
            },
        ),
    ]
