# Generated by Django 4.0.4 on 2022-07-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_remove_comment_upvote_comment_url_like_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='story_photo',
            name='name',
        ),
    ]
