# Generated by Django 4.0.4 on 2022-07-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_remove_comment_photo_name_remove_story_photo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
