# Generated by Django 4.0.4 on 2022-07-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='upvote_total',
        ),
    ]
