# Generated by Django 4.0.4 on 2022-07-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_remove_story_upvote_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
    ]
