# Generated by Django 4.0.4 on 2022-07-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_remove_comment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
