# Generated by Django 4.0.4 on 2022-07-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_comment_likes_count_story_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='story',
            new_name='story_id',
        ),
    ]
