# Generated by Django 4.0.4 on 2022-07-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_rename_comment_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='story',
            name='likes_count',
        ),
    ]
