# Generated by Django 4.0.4 on 2022-07-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_follow'),
        ('story', '0017_remove_comment_likes_count_remove_story_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='story_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_story', to='story.story'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='comment_photo',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_photo', to='story.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='story.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='story',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_story', to='story.story'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='story_photo',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_photo', to='story.story'),
        ),
    ]
