# Generated by Django 4.0.4 on 2022-08-01 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_alter_comment_story_id_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_photo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='story_photo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
