# Generated by Django 4.0.4 on 2022-08-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0020_alter_comment_photo_time_alter_story_photo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_photo',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story_photo',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
