# Generated by Django 4.0.4 on 2022-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_alter_comment_photo_time_alter_story_photo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tag_username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
