# Generated by Django 4.0.4 on 2022-05-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
