# Generated by Django 4.0.4 on 2022-05-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
