# Generated by Django 4.0.4 on 2022-06-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_user_profile_user_id_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='尚未填寫完整自我介紹', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, default='尚未填寫簡介', max_length=200, null=True),
        ),
    ]
